import * as React from 'react';
import { z } from 'zod';
import { AlignLeft, ListRestart } from 'lucide-react';

import { Button } from '@/ui/button';
import { EmojiPickerButton } from '@/ui/emoji-picker-button';
import {
  ClearFormattingButton,
  FormatBarButton,
  FormatBarDivider,
  InsertVariableButton,
  TextFormatBar,
} from '@/ui/text-format-bar';
import { AiFeaturesButton } from '@/ui/ai-features-menu';
import { FormatIcon, WA_TEXT_FORMATS } from '@/ui/text-format-icons';
import { Field } from '@/ui/field';
import { Textarea } from '@/ui/textarea';
import { SubscriberFieldCombobox } from '@/ui/subscriber-field-combobox';
import { LIMITS } from '@/core/limits';
import { matchSubscriberField } from '@/core/subscriber-fields';
import type { BlockPlugin, ValidationIssue } from '@/core/types';
import { useSubscriberFields } from '@/hooks/use-subscriber-fields';
import { processWaText, type WaAiAction } from '@/core/ai';
import { clearWaFormatting } from '@/core/text-format';
import {
  analyzeVariables,
  exampleRow,
  insertVariableAt,
  renumberVariables,
  uniqueVariables,
  type VariableMap,
} from '@/core/variables';
import { renderWaText } from '@/preview/renderWaText';

const schema = z.object({
  text: z.string(),
  // Optional: drafts/imports may lack it; every consumer treats absence as {}.
  variables: z
    .record(
      z.string(),
      z.object({
        name: z.string().optional(),
        example: z.string().optional(),
        source: z.string().optional(),
      }),
    )
    .optional(),
});

type Data = z.infer<typeof schema>;

/** URL / phone detection for the live helper hints (never blocking). */
const URL_IN_TEXT_RE = /https?:\/\/[^\s]+/g;
const PHONE_IN_TEXT_RE = /\+\d[\d\s().-]{7,}\d/g;

export const bodyPlugin: BlockPlugin<Data> = {
  type: 'body',
  slot: 'body',
  meta: {
    label: 'Body',
    description: 'Main message, up to 1024 characters, variables and formatting',
    group: 'Body',
    icon: AlignLeft,
    keywords: ['text', 'message', 'content'],
  },
  schema,
  defaults: () => ({ text: '', variables: {} }),
  availableIn: (category) =>
    category === 'AUTHENTICATION'
      ? {
          available: false,
          reason: 'Authentication bodies are generated by Meta — use the Authentication body',
        }
      : { available: true },
  validate: (data) => {
    const issues: ValidationIssue[] = [];
    if (!data.text.trim()) {
      issues.push({
        severity: 'error',
        slot: 'body',
        code: 'body/required',
        message: 'Body text is required',
      });
    }
    if (data.text.length > LIMITS.BODY_TEXT_MAX) {
      issues.push({
        severity: 'error',
        slot: 'body',
        code: 'body/too-long',
        message: `Body exceeds ${LIMITS.BODY_TEXT_MAX} characters`,
      });
    }
    const analysis = analyzeVariables(data.text, data.variables ?? {});
    if (!analysis.sequential) {
      issues.push({
        severity: 'error',
        slot: 'body',
        code: 'body/variables-not-sequential',
        message: 'Variables must be numbered sequentially from {{1}} with no gaps',
      });
    }
    if (/^\s*\{\{\s*\d+\s*\}\}/.test(data.text) || /\{\{\s*\d+\s*\}\}\s*$/.test(data.text)) {
      issues.push({
        severity: 'warning',
        slot: 'body',
        code: 'body/variable-at-edge',
        message: 'Meta may reject bodies that start or end with a variable',
      });
    }
    for (const n of analysis.duplicated) {
      issues.push({
        severity: 'warning',
        slot: 'body',
        code: 'body/variable-duplicated',
        message: `Variable {{${n}}} is used more than once`,
      });
    }
    for (const n of analysis.used) {
      if (!((data.variables ?? {})[String(n)]?.example ?? '').trim()) {
        issues.push({
          severity: 'warning',
          slot: 'body',
          code: 'body/variable-example-missing',
          message: `Add an example value for {{${n}}} (required by Meta review)`,
        });
      }
    }
    for (const bad of analysis.malformed) {
      issues.push({
        severity: 'error',
        slot: 'body',
        code: 'body/malformed-variable',
        message: `"${bad}" is not a valid variable — use {{1}}, {{2}}, …`,
      });
    }
    return issues;
  },
  Editor: function BodyEditor({ value, onChange }) {
    const analysis = analyzeVariables(value.text, value.variables ?? {});
    const detectedUrls = value.text.match(URL_IN_TEXT_RE) ?? [];
    const detectedPhones = value.text.match(PHONE_IN_TEXT_RE) ?? [];
    const textareaRef = React.useRef<HTMLTextAreaElement>(null);
    // Last known caret/selection, so inserts land in place even after the
    // textarea loses focus to a popover (the emoji picker's cells blur it).
    const selectionRef = React.useRef({ start: 0, end: 0 });
    const rememberSelection = () => {
      const el = textareaRef.current;
      if (!el) return;
      selectionRef.current = { start: el.selectionStart ?? 0, end: el.selectionEnd ?? 0 };
    };
    const subscriberFields = useSubscriberFields();

    const setVariableMeta = (
      n: number,
      patch: { name?: string; example?: string; source?: string },
    ) => {
      onChange({
        ...value,
        variables: {
          ...(value.variables ?? {}),
          [String(n)]: { ...(value.variables ?? {})[String(n)], ...patch },
        },
      });
    };

    // Splice text into the body at the caret (or over the current selection),
    // keep the controlled value in sync, and position the caret — all
    // synchronously. Using setRangeText (instead of onChange + a deferred
    // setSelectionRange) avoids a race with the controlled re-render driven by
    // the external store, which would otherwise fling the caret to the end.
    // When the textarea isn't focused, fall back to the last remembered
    // selection (append only when there was never one). `make` may return
    // from/to to replace a different range than the selection (whole-field
    // operations); selStart/selEnd are relative to that range's start.
    const spliceText = (
      make: (ctx: { start: number; end: number; text: string }) => {
        insert: string;
        selStart: number;
        selEnd: number;
        from?: number;
        to?: number;
      },
    ) => {
      const el = textareaRef.current;
      const text = value.text;
      const focused = !!el && document.activeElement === el;
      const fallback =
        selectionRef.current.end <= text.length
          ? selectionRef.current
          : { start: text.length, end: text.length };
      const start = focused ? (el.selectionStart ?? text.length) : fallback.start;
      const end = focused ? (el.selectionEnd ?? text.length) : fallback.end;
      const { insert, selStart, selEnd, from = start, to = end } = make({ start, end, text });
      if (el) {
        el.focus();
        // setRangeText mutates el.value in place; because React receives the
        // exact same string, its controlled-value guard skips the DOM write and
        // the selection we set below survives the re-render.
        el.setRangeText(insert, from, to, 'end');
        el.setSelectionRange(from + selStart, from + selEnd);
        selectionRef.current = { start: from + selStart, end: from + selEnd };
        onChange({ ...value, text: el.value });
      } else {
        selectionRef.current = { start: from + selEnd, end: from + selEnd };
        onChange({ ...value, text: text.slice(0, from) + insert + text.slice(to) });
      }
    };

    // Wrap the current selection (or a placeholder) in a WhatsApp marker and
    // keep the inner text selected so it reads like a WYSIWYG toggle.
    const applyFormat = (before: string, after: string) =>
      spliceText(({ start, end, text }) => {
        const inner = text.slice(start, end) || 'text';
        return {
          insert: before + inner + after,
          selStart: before.length,
          selEnd: before.length + inner.length,
        };
      });

    // Strip WhatsApp markers from the selection — or the whole field when
    // nothing is selected — and keep the cleared range selected.
    const clearFormatting = () =>
      spliceText(({ start, end, text }) => {
        const [from, to] = start === end ? [0, text.length] : [start, end];
        const insert = clearWaFormatting(text.slice(from, to));
        return { insert, from, to, selStart: 0, selEnd: insert.length };
      });

    // Send the selection (or the whole body) through the host's AI backend
    // and splice the result over the same range. The menu owns loading and
    // error UI; edits made while the request was in flight abort the splice.
    const runAiAction = async (action: WaAiAction) => {
      const el = textareaRef.current;
      const text = value.text;
      const focused = !!el && document.activeElement === el;
      const fallback =
        selectionRef.current.end <= text.length
          ? selectionRef.current
          : { start: text.length, end: text.length };
      const start = focused ? (el.selectionStart ?? 0) : fallback.start;
      const end = focused ? (el.selectionEnd ?? 0) : fallback.end;
      const [from, to] = start === end ? [0, text.length] : [start, end];
      const source = text.slice(from, to);
      if (!source.trim()) throw new Error('Write some text first.');
      const insert = await processWaText(source, action);
      if (textareaRef.current && textareaRef.current.value !== text) {
        throw new Error('The text changed while AI was working — try again.');
      }
      spliceText(() => ({ insert, from, to, selStart: 0, selEnd: insert.length }));
    };

    // Insert a variable at the caret and renumber so placeholders stay
    // sequential 1..n by position. This rewrites the whole text (numbers may
    // shift), so we replace the field's full contents and restore the caret in
    // one synchronous pass, feeding React the same string to avoid a re-render
    // caret jump.
    const insertVariable = () => {
      const el = textareaRef.current;
      const text = value.text;
      const focused = !!el && document.activeElement === el;
      const fallback =
        selectionRef.current.end <= text.length
          ? selectionRef.current
          : { start: text.length, end: text.length };
      const start = focused ? (el.selectionStart ?? text.length) : fallback.start;
      const end = focused ? (el.selectionEnd ?? text.length) : fallback.end;
      const result = insertVariableAt(text, value.variables ?? {}, start, end);
      if (el) {
        el.focus();
        el.setRangeText(result.text, 0, el.value.length, 'end');
        el.setSelectionRange(result.caret, result.caret);
        selectionRef.current = { start: result.caret, end: result.caret };
        onChange({ ...value, text: el.value, variables: result.map });
      } else {
        onChange({ ...value, text: result.text, variables: result.map });
      }
    };

    return (
      <div className="flex flex-col gap-4">
        <Field label="Message text" counter={`${value.text.length}/${LIMITS.BODY_TEXT_MAX}`}>
          <TextFormatBar>
            {WA_TEXT_FORMATS.map((f) => (
              <FormatBarButton
                key={f.label}
                aria-label={f.label}
                title={f.label}
                onClick={() => applyFormat(f.before, f.after)}
              >
                <FormatIcon icon={f.icon} />
              </FormatBarButton>
            ))}
            <FormatBarDivider />
            <InsertVariableButton onInsert={insertVariable} />
            <FormatBarDivider />
            <EmojiPickerButton
              onPick={(native) =>
                spliceText(() => ({
                  insert: native,
                  selStart: native.length,
                  selEnd: native.length,
                }))
              }
            />
            <FormatBarDivider />
            <AiFeaturesButton onRun={runAiAction} />
            <FormatBarDivider />
            <ClearFormattingButton onClear={clearFormatting} />
          </TextFormatBar>
          <Textarea
            ref={textareaRef}
            value={value.text}
            onChange={(e) => onChange({ ...value, text: e.target.value })}
            onSelect={rememberSelection}
            onKeyUp={rememberSelection}
            onBlur={rememberSelection}
            rows={8}
            className="min-h-32"
            placeholder={'Hi {{1}}, your order {{2}} has shipped! 🎉'}
            aria-label="Body text"
          />
        </Field>

        {!analysis.sequential && (
          <div className="flex flex-wrap items-center gap-2">
            <Button
              type="button"
              variant="secondary"
              size="sm"
              onClick={() => {
                const result = renumberVariables(value.text, value.variables ?? {});
                onChange({ text: result.text, variables: result.map });
              }}
            >
              <ListRestart className="size-3.5" /> Renumber
            </Button>
          </div>
        )}

        {analysis.used.length > 0 && (
          <div className="flex flex-col gap-3">
            <div className="text-xs font-medium text-muted-foreground">Variables</div>
            {analysis.used.map((n) => (
              <div key={n} className="flex flex-col gap-1.5 rounded-md border border-border p-2.5">
                <div className="flex items-center justify-between gap-2">
                  <div className="flex min-w-0 items-center gap-1.5">
                    <span className="badge">{`{{${n}}}`}</span>
                    {analysis.duplicated.includes(n) && <span className="badge">used twice</span>}
                  </div>
                  <input
                    value={(value.variables ?? {})[String(n)]?.name ?? ''}
                    onChange={(e) => setVariableMeta(n, { name: e.target.value })}
                    placeholder="Label"
                    aria-label={`Variable ${n} label`}
                    className="badge badge--whatsapp"
                  />
                </div>
                <SubscriberFieldCombobox
                  options={subscriberFields}
                  value={matchSubscriberField((value.variables ?? {})[String(n)], subscriberFields)}
                  onChange={(option) =>
                    setVariableMeta(n, {
                      example: option.example,
                      source: option.token,
                    })
                  }
                  placeholder="Map to subscriber field…"
                  aria-label={`Variable ${n} subscriber field`}
                />
              </div>
            ))}
          </div>
        )}

        {(detectedUrls.length > 0 || detectedPhones.length > 0) && (
          <div className="text-xs text-muted-foreground">
            {detectedUrls.length > 0 && <div>Detected link: {detectedUrls.join(', ')}</div>}
            {detectedPhones.length > 0 && <div>Detected phone: {detectedPhones.join(', ')}</div>}
          </div>
        )}
      </div>
    );
  },
  Preview: function BodyPreview({ data, ctx }) {
    return (
      <div
        className={`whitespace-pre-wrap break-words px-[9px] py-[5px] text-[14.2px] leading-[19px] ${
          ctx.dark ? 'text-[#e9edef]' : 'text-[#111b21]'
        }`}
      >
        {data.text ? (
          renderWaText(data.text, ctx.resolveVariable)
        ) : (
          <span className="opacity-40">Write your message…</span>
        )}
      </div>
    );
  },
  toMeta: (data) => {
    const vars = uniqueVariables(data.text);
    return {
      type: 'BODY',
      text: data.text,
      ...(vars.length > 0
        ? { example: { body_text: [exampleRow(data.text, (data.variables ?? {}) as VariableMap)] } }
        : {}),
    };
  },
  fromMeta: (component, template) => {
    if (String(component.type).toUpperCase() !== 'BODY') return null;
    // Authentication bodies belong to the body-auth plugin.
    if (template.category === 'AUTHENTICATION') return null;
    const text = typeof component.text === 'string' ? component.text : '';
    const variables: Data['variables'] = {};
    const rows =
      (component.example as { body_text?: string[][] } | undefined)?.body_text?.[0] ?? [];
    uniqueVariables(text).forEach((n, i) => {
      const example = rows[i];
      if (example !== undefined) variables[String(n)] = { example };
    });
    return { text, variables };
  },
};
