import * as React from 'react';
import { z } from 'zod';
import { AlignLeft, ListRestart, Plus } from 'lucide-react';

import { Badge } from '@/ui/badge';
import { Button } from '@/ui/button';
import { Field } from '@/ui/field';
import { Input } from '@/ui/input';
import { Textarea } from '@/ui/textarea';
import { LIMITS } from '@/core/limits';
import type { BlockPlugin, ValidationIssue } from '@/core/types';
import {
  analyzeVariables,
  exampleRow,
  nextVariableNumber,
  renumberVariables,
  uniqueVariables,
  type VariableMap,
} from '@/core/variables';
import { renderWaText } from '@/preview/renderWaText';

const schema = z.object({
  text: z.string(),
  // Optional: drafts/imports may lack it; every consumer treats absence as {}.
  variables: z.record(z.string(), z.object({ name: z.string().optional(), example: z.string().optional() })).optional(),
});

type Data = z.infer<typeof schema>;

/** URL / phone detection for the live helper hints (never blocking). */
const URL_IN_TEXT_RE = /https?:\/\/[^\s]+/g;
const PHONE_IN_TEXT_RE = /\+\d[\d\s().-]{7,}\d/g;

export const bodyPlugin: BlockPlugin<Data> = {
  type: 'body',
  slot: 'body',
  meta: {
    label: 'Body',
    description: 'Main message, up to 1024 characters, variables and formatting',
    group: 'Body',
    icon: AlignLeft,
    keywords: ['text', 'message', 'content'],
  },
  schema,
  defaults: () => ({ text: '', variables: {} }),
  availableIn: (category) =>
    category === 'AUTHENTICATION'
      ? { available: false, reason: 'Authentication bodies are generated by Meta — use the Authentication body' }
      : { available: true },
  validate: (data) => {
    const issues: ValidationIssue[] = [];
    if (!data.text.trim()) {
      issues.push({ severity: 'error', slot: 'body', code: 'body/required', message: 'Body text is required' });
    }
    if (data.text.length > LIMITS.BODY_TEXT_MAX) {
      issues.push({
        severity: 'error',
        slot: 'body',
        code: 'body/too-long',
        message: `Body exceeds ${LIMITS.BODY_TEXT_MAX} characters`,
      });
    }
    const analysis = analyzeVariables(data.text, data.variables ?? {});
    if (!analysis.sequential) {
      issues.push({
        severity: 'error',
        slot: 'body',
        code: 'body/variables-not-sequential',
        message: 'Variables must be numbered sequentially from {{1}} with no gaps',
      });
    }
    if (/^\s*\{\{\s*\d+\s*\}\}/.test(data.text) || /\{\{\s*\d+\s*\}\}\s*$/.test(data.text)) {
      issues.push({
        severity: 'warning',
        slot: 'body',
        code: 'body/variable-at-edge',
        message: 'Meta may reject bodies that start or end with a variable',
      });
    }
    for (const n of analysis.duplicated) {
      issues.push({
        severity: 'warning',
        slot: 'body',
        code: 'body/variable-duplicated',
        message: `Variable {{${n}}} is used more than once`,
      });
    }
    for (const n of analysis.used) {
      if (!((data.variables ?? {})[String(n)]?.example ?? '').trim()) {
        issues.push({
          severity: 'warning',
          slot: 'body',
          code: 'body/variable-example-missing',
          message: `Add an example value for {{${n}}} (required by Meta review)`,
        });
      }
    }
    for (const bad of analysis.malformed) {
      issues.push({
        severity: 'error',
        slot: 'body',
        code: 'body/malformed-variable',
        message: `"${bad}" is not a valid variable — use {{1}}, {{2}}, …`,
      });
    }
    return issues;
  },
  Editor: function BodyEditor({ value, onChange }) {
    const analysis = analyzeVariables(value.text, value.variables ?? {});
    const detectedUrls = value.text.match(URL_IN_TEXT_RE) ?? [];
    const detectedPhones = value.text.match(PHONE_IN_TEXT_RE) ?? [];

    const setVariableMeta = (n: number, patch: { name?: string; example?: string }) => {
      onChange({
        ...value,
        variables: { ...(value.variables ?? {}), [String(n)]: { ...(value.variables ?? {})[String(n)], ...patch } },
      });
    };

    return (
      <div className="flex flex-col gap-4">
        <Field
          label="Message text"
          counter={`${value.text.length}/${LIMITS.BODY_TEXT_MAX}`}
          hint="*bold* _italic_ ~strike~ ```mono``` · line breaks and emoji supported"
        >
          <Textarea
            value={value.text}
            onChange={(e) => onChange({ ...value, text: e.target.value })}
            rows={8}
            placeholder={'Hi {{1}}, your order {{2}} has shipped! 🎉'}
            aria-label="Body text"
          />
        </Field>

        <div className="flex flex-wrap items-center gap-2">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => onChange({ ...value, text: `${value.text}{{${nextVariableNumber(value.text)}}}` })}
          >
            <Plus className="size-3.5" /> Variable
          </Button>
          {!analysis.sequential && (
            <Button
              type="button"
              variant="secondary"
              size="sm"
              onClick={() => {
                const result = renumberVariables(value.text, value.variables ?? {});
                onChange({ text: result.text, variables: result.map });
              }}
            >
              <ListRestart className="size-3.5" /> Renumber
            </Button>
          )}
        </div>

        {analysis.used.length > 0 && (
          <div className="flex flex-col gap-3">
            <div className="text-xs font-medium text-muted-foreground">Variables</div>
            {analysis.used.map((n) => (
              <div key={n} className="flex flex-col gap-1.5 rounded-md border border-border p-2.5">
                <div className="flex items-center gap-1.5">
                  <Badge variant="secondary">{`{{${n}}}`}</Badge>
                  {analysis.duplicated.includes(n) && <Badge variant="outline">used twice</Badge>}
                </div>
                <Input
                  value={(value.variables ?? {})[String(n)]?.name ?? ''}
                  onChange={(e) => setVariableMeta(n, { name: e.target.value })}
                  placeholder="Label (e.g. Customer name)"
                  aria-label={`Variable ${n} label`}
                />
                <Input
                  value={(value.variables ?? {})[String(n)]?.example ?? ''}
                  onChange={(e) => setVariableMeta(n, { example: e.target.value })}
                  placeholder="Example value (required by Meta)"
                  aria-label={`Variable ${n} example`}
                />
              </div>
            ))}
          </div>
        )}

        {(detectedUrls.length > 0 || detectedPhones.length > 0) && (
          <div className="text-xs text-muted-foreground">
            {detectedUrls.length > 0 && <div>Detected link: {detectedUrls.join(', ')}</div>}
            {detectedPhones.length > 0 && <div>Detected phone: {detectedPhones.join(', ')}</div>}
          </div>
        )}
      </div>
    );
  },
  Preview: function BodyPreview({ data, ctx }) {
    return (
      <div
        className={`whitespace-pre-wrap break-words px-[9px] py-[5px] text-[14.2px] leading-[19px] ${
          ctx.dark ? 'text-[#e9edef]' : 'text-[#111b21]'
        }`}
      >
        {data.text ? renderWaText(data.text, ctx.resolveVariable) : <span className="opacity-40">Write your message…</span>}
      </div>
    );
  },
  toMeta: (data) => {
    const vars = uniqueVariables(data.text);
    return {
      type: 'BODY',
      text: data.text,
      ...(vars.length > 0 ? { example: { body_text: [exampleRow(data.text, (data.variables ?? {}) as VariableMap)] } } : {}),
    };
  },
  fromMeta: (component, template) => {
    if (String(component.type).toUpperCase() !== 'BODY') return null;
    // Authentication bodies belong to the body-auth plugin.
    if (template.category === 'AUTHENTICATION') return null;
    const text = typeof component.text === 'string' ? component.text : '';
    const variables: Data['variables'] = {};
    const rows = (component.example as { body_text?: string[][] } | undefined)?.body_text?.[0] ?? [];
    uniqueVariables(text).forEach((n, i) => {
      const example = rows[i];
      if (example !== undefined) variables[String(n)] = { example };
    });
    return { text, variables };
  },
};
