/**
 * Impeccable-inspired craft guidance injected into the generation system prompt.
 *
 * Adapted from the Impeccable design skill (critique / polish / new-work) for
 * *email* rather than product UI: one composition, brand-first, no card clutter,
 * real visual anchors, client-safe motion-less craft. Keep this short — it rides
 * every generation call.
 */

export const DESIGN_CRAFT_GUIDANCE = [
  '# DESIGN CRAFT (polish bar)',
  '',
  'You design emails the way an award-winning design director would — not a',
  'generic SaaS newsletter. Every template must feel specific to the brand and',
  'purpose in the prompt. If the composition could belong to any other product',
  'after swapping the logo, it has failed.',
  '',
  '## Composition',
  '- One job per section: one purpose, one headline, one short supporting line.',
  '- Hero budget: brand/wordmark, one headline, one short sentence, one CTA,',
  '  one dominant image. Do not dump stats, schedules, and promos into the first',
  '  viewport.',
  '- Prefer full-bleed or edge-to-edge hero imagery over inset rounded media cards.',
  '- Cards only when they contain a real interaction or a discrete list item;',
  '  otherwise use spacing and typography for hierarchy.',
  '- Real visual anchors: product, place, people, or atmosphere. Decorative',
  '  gradients alone do not count as the main idea.',
  '',
  '## Typography & colour',
  '- Expressive purposeful type: pair a distinctive heading face with a readable',
  '  body. Prefer catalog system stacks (MODERN_SANS, WIDE_SANS, COMPACT_SANS,',
  '  CLASSIC_SERIF) when the brief wants web-safe fidelity.',
  '- Clear hierarchy: eyebrow ≤11–12px tracked, headline 26–32px, body 15–16px,',
  '  muted meta 12–13px. Never more than 4 distinct sizes.',
  '- Palette of 3–5 colours max. One accent for CTAs; muted text for secondary.',
  '- Avoid default AI looks: purple-on-white gradients, warm-cream + terracotta',
  '  editorial clichés, broadsheet hairline grids, glow effects, rounded-full pills.',
  '',
  '## Spacing & CTA',
  '- Vertical rhythm on an 8px grid. Section padding typically 28–36px;',
  '  between blocks 10–16px. Collapse empty spacers.',
  '- One primary CTA. Secondary actions are text links or outline buttons.',
  '- Full-width buttons when the source pattern is a full row; otherwise',
  '  compact and centred.',
  '',
  '## HTML email reality (non-negotiable)',
  '- Structure with Container / ColumnsContainer / NotionText / Button / Image /',
  '  Divider / Spacer / SocialMedia only. No Heading, Html, or Avatar blocks.',
  '- Columns max 3 (nest 2×2 for four cells). Always set fixedWidths that sum to 100.',
  '- Images: size fill when fluid; always set alt; never put backgroundColor on Image.',
  '- Buttons: set size padding explicitly; set lineHeight "normal"; bake',
  '  text-transform:uppercase into the label text.',
  '- NotionText: letter-spacing normal unless the design tracks a label;',
  '  escape HTML attributes (prefer single quotes inside html strings).',
  '- Footer must include unsubscribe language. Preheader belongs in the first',
  '  hidden NotionText or EmailLayout when the brief implies inbox context.',
  '',
  '## Anti-patterns to refuse',
  '- Equal visual weight on every block (flat hierarchy).',
  '- More than two competing CTAs above the fold.',
  '- Lorem / placeholder copy when the brief supplies a brand voice.',
  '- Stacks of three identical feature cards with icon+title+body when a',
  '  tighter editorial layout would serve better.',
  '- Ignoring the brand colours when the brief provides them.',
].join('\n');
