import { BaseZodDictionary, BlockConfiguration, DocumentBlocksDictionary } from '../utils';

import ClientOnly from './ClientOnly';

type BlockComponentRootProps<T extends BaseZodDictionary> = BlockConfiguration<T> & {
  isNotClient?: boolean;
};

/**
 * @param blocks Main DocumentBlocksDictionary
 * @returns React component that can render a BlockConfiguration that is compatible with blocks
 *
 * Unknown `type` values render as `null` with a single dev-time warning per
 * type instead of throwing. This keeps the Reader resilient to templates
 * generated by AI backends that emit block types the Reader does not
 * register (e.g. `SocialMedia` when embedding the Reader outside the
 * editor). The editor-side dictionary registers all insertable types, so
 * Apply still produces a correctly-rendered email after the user loads the
 * template into the builder.
 */
const warnedUnknownTypes = new Set<string>();

export default function buildBlockComponent<T extends BaseZodDictionary>(blocks: DocumentBlocksDictionary<T>) {
  return function BlockComponent(props: BlockComponentRootProps<T>) {
    const { type, data, blockId } = props;
    const entry = blocks[type];
    if (entry === undefined) {
      if (typeof type === 'string' && !warnedUnknownTypes.has(type)) {
        warnedUnknownTypes.add(type);

        console.warn(
          `[email-builder] Unknown block type "${type}" (blockId="${blockId ?? '<unknown>'}") — rendering as empty. Register the block in the dictionary to render it.`
        );
      }
      return null;
    }
    const Component = entry.Component;
    if (props.isNotClient) {
      return <Component {...data} blockId={blockId} isNotClient={props.isNotClient} />;
    }
    return (
      <ClientOnly>
        <Component {...data} blockId={blockId} />
      </ClientOnly>
    );
  };
}
